config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  root 'wallets#index'

  resources :order_transactions, only: :create

  resources :wallets, only: :show
=======
  devise_for :users,
    skip: [:sessions, :registrations, :passwords],
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  authenticated nil, lambda { |u| u.regular? } do
    root 'users#show', as: :authenticated_user_root
  end

  authenticated nil, lambda { |u| u.merchant? } do
    root 'order_transactions#new', as: :authenticated_merchant_root
  end

  authenticated nil, lambda { |u| u.bank? } do
    root 'order_transactions#index', as: :authenticated_bank_root
  end

  root 'pages#home'

  resources :users, only: [] do
    post :sign_in_as_merchant, on: :collection
    post :sign_in_as_bank, on: :collection
  end

  resources :order_transactions, only: [:new, :create, :index] do
    get :redeem, on: :collection
  end
>>>>>>> airwaze-mvp/master
end

app/views/shared/_flash.html.haml
<<<<<<< HEAD
.container.center
- if flash[:error].present?
  .alert.alert-danger.alert-dismissible.fade.show{role: 'alert'}
    = flash[:error]
    %button.close{'data-dismiss': 'alert'}
      %span &times;
  </button>
- elsif flash[:notice].present?
  .alert.alert-success.alert-dismissible.fade.show{role: 'alert'}
    = flash[:notice]
    %button.close{'data-dismiss': 'alert'}
      %span &times;
=======
- css_classes = {alert: 'alert-danger', notice: 'alert-success'}

.container.center.mt-2.fixed-top
  - flash.each do |key, message|
    .alert.alert-dismissible.fade.show{role: 'alert', class: css_classes[key.to_sym]}
      = message
      %button.close{'data-dismiss': 'alert'}
        %span &times;

:javascript
  $('.alert-success').delay(1500).fadeTo(2000, 0, function(){
    $('.alert-success').alert('close')
  });
>>>>>>> airwaze-mvp/master

app/views/shared/_footer.html.haml
.container
  %p= "© #{t('app.title')} #{Date.today.year}"

app/views/shared/_header.html.haml
.container.d-flex.justify-content-between.align-items-center
  %h5.m-0
    = link_to t('app.title'), root_path, class: 'text-white'
  .text-right
    - if user_signed_in?
      - if current_user.regular?
        %img.avatar.mr-2{src: current_user.image_url}
      = link_to 'Sign Out', destroy_user_session_path, method: :delete,
        class: 'btn btn-outline-light btn-sm'
      - if current_user.regular?
        = link_to 'Redeem', redeem_order_transactions_path,
          class: 'btn btn-primary btn-sm'
    - else
      = link_to 'Sign in with Google', user_google_oauth2_omniauth_authorize_path,
        class: 'btn btn-outline-light btn-sm'