config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  root 'wallets#index'

  resources :order_transactions, only: :create

  resources :wallets, only: :show
=======
  devise_for :users,
    skip: [:sessions, :registrations, :passwords],
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  authenticated nil, lambda { |u| u.regular? } do
    root 'users#show', as: :authenticated_user_root
  end

  authenticated nil, lambda { |u| u.merchant? } do
    root 'order_transactions#new', as: :authenticated_merchant_root
  end

  authenticated nil, lambda { |u| u.bank? } do
    root 'order_transactions#index', as: :authenticated_bank_root
  end

  root 'pages#home'

  resources :users, only: [] do
    post :sign_in_as_merchant, on: :collection
    post :sign_in_as_bank, on: :collection
  end

  resources :order_transactions, only: [:new, :create, :index] do
    get :redeem, on: :collection
  end
>>>>>>> airwaze-mvp/master
end

app/views/pages/home.html.haml
= content_for :header_hidden, true

.my-auto.w-100.text-center
  %h1= t('app.title')
  = link_to 'Sign in with Google', user_google_oauth2_omniauth_authorize_path,
    class: 'btn btn-outline-light btn-sm'
  %br
  = link_to 'Sign in as Merchant', sign_in_as_merchant_users_path,
    method: :post, class: 'btn btn-primary btn-sm mt-2'
  %br
  = link_to 'Sign in as Juvo Air Time Bank', sign_in_as_bank_users_path,
    method: :post, class: 'btn btn-success btn-sm mt-2'