config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  root 'wallets#index'

  resources :order_transactions, only: :create

  resources :wallets, only: :show
=======
  devise_for :users,
    skip: [:sessions, :registrations, :passwords],
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  authenticated nil, lambda { |u| u.regular? } do
    root 'users#show', as: :authenticated_user_root
  end

  authenticated nil, lambda { |u| u.merchant? } do
    root 'order_transactions#new', as: :authenticated_merchant_root
  end

  authenticated nil, lambda { |u| u.bank? } do
    root 'order_transactions#index', as: :authenticated_bank_root
  end

  root 'pages#home'

  resources :users, only: [] do
    post :sign_in_as_merchant, on: :collection
    post :sign_in_as_bank, on: :collection
  end

  resources :order_transactions, only: [:new, :create, :index] do
    get :redeem, on: :collection
  end
>>>>>>> airwaze-mvp/master
end

app/controllers/order_transactions_controller.rb
class OrderTransactionsController < ApplicationController
<<<<<<< HEAD
  def create
    order_transaction_params = params
      .require(:order_transaction)
      .permit(:issuer_wallet_id, :receiver_wallet_id, :amount)

    resource = OrderTransaction.new(order_transaction_params)
    resource.validate!

    ApplicationRecord.transaction do
      amount = resource.amount.to_i

      case resource.receiver_wallet.kind.to_sym
      when :user_wallet
        resource.issuer_wallet.juvo_token_balance -= amount
        resource.receiver_wallet.juvo_token_balance += amount

        flash[:notice] = success_message =
          "Success! Issued #{amount} Juvo Tokens \
          to #{resource.receiver_wallet.name}"
      when :merchant_wallet
        resource.issuer_wallet.juvo_token_balance -= amount
        resource.issuer_wallet.air_time_token_balance += amount
        resource.receiver_wallet.juvo_token_balance += amount

        flash[:notice] = success_message =
          "Success! Received #{amount} Air Time Tokens \
          in exchange of #{amount} Juvo Tokens"
      end

      resource.issuer_wallet.save!
      resource.receiver_wallet.save!
    end
  rescue => e
    flash[:error] = e.message
  ensure
    redirect_to resource.issuer_wallet
=======
  view_accessor :resource, :resources
  view_accessor :wallets, :amounts

  before_action :authenticate_user!

  def index
    self.resources = OrderTransaction.sent_or_received(current_user).order(created_at: :desc)
  end

  def new
    only_for_users! :merchant, :regular

    self.resource = OrderTransaction.new
    self.amounts = (0..1000).step(100)
    self.wallets = Wallet.except_user(current_user)
      .except_user(User.bank.first)
      .where(currency_id: current_user.main_sender_wallet.currency)
  end

  def redeem
    only_for_users! :regular

    self.resource = OrderTransaction.new(receiver_wallet: User.bank.first.wallets.for_currency(Currency.juvo_token.first).first)
    self.amounts = (0..1000).step(100)
  end

  def create
    only_for_users! :merchant, :regular

    order_transaction_params = params
      .require(:order_transaction)
      .permit(:receiver_wallet_id, :amount)
      .merge(issuer_wallet: current_user.main_sender_wallet)

    ApplicationRecord.transaction do
      case Wallet.find_by_id!(order_transaction_params[:receiver_wallet_id]).user.kind.to_sym
      when :regular, :merchant
        resource = process_order_transaction!(order_transaction_params)
        flash[:notice] =
          "Success! Issued #{resource.amount} #{resource.currency.name_plural.titleize} \
          to #{resource.receiver_wallet.user.name}"
      when :bank
        juvo_resource = process_order_transaction!(order_transaction_params)

        issuer_wallet = User.bank.first.main_sender_wallet
        days_of_air_time_resource = process_order_transaction!(
          issuer_wallet: issuer_wallet,
          receiver_wallet: current_user.wallets.for_currency(issuer_wallet.currency).first,
          amount: juvo_resource.amount
        )

        flash[:notice] =
          "Success! Received #{days_of_air_time_resource.amount} #{days_of_air_time_resource.currency.name_plural.titleize} \
          in exchange of #{juvo_resource.amount} #{juvo_resource.currency.name_plural.titleize}"
      end
    end

    redirect_to root_path
  rescue => e
    flash[:alert] = e.message
    redirect_back fallback_location: resource
  end

  private

  def process_order_transaction!(params)
    order_transaction = OrderTransaction.new(params.merge(currency: params[:issuer_wallet].currency))
    order_transaction.save!

    order_transaction.issuer_wallet.balance -= order_transaction.amount
    order_transaction.receiver_wallet.balance += order_transaction.amount

    order_transaction.issuer_wallet.save!
    order_transaction.receiver_wallet.save!
    order_transaction
>>>>>>> airwaze-mvp/master
  end
end

app/helpers/order_transactions_helper.rb
module OrderTransactionsHelper
end

app/views/order_transactions/index.html.haml
- if current_user.bank?
  .col-lg-5.my-auto.mx-auto.text-center
    %h2= current_user.name
.col-12.col-md-5.my-auto.mx-auto.text-center
  - if resources.empty?
    %h5 No Transactions
  %ul.list-group
    - resources.each do |resource|
      %li.list-group-item.d-flex.justify-content-between.align-items-center.text-left
        - if resource.issuer_wallet.user == current_user
          = "Sent to #{resource.receiver_wallet.user.name}"
        - else
          = "Received from #{resource.issuer_wallet.user.name}"
        %span.text-right
          = resource.amount
          = resource.currency.name_plural.titleize

app/views/order_transactions/new.html.haml
.col-lg-5.my-auto.mx-auto
  - if current_user.merchant?
    .text-center
      = render 'users/qr_code', resource: current_user
      %h2= current_user.name
  = form_for resource do |f|
    .form-group
      .d-flex.justify-content-between
        = f.label 'Recipient'
        %label.qr-code-button
          .btn.btn-outline-light.btn-sm Scan QR Code
          %input{type: 'file',
            accept: 'image/*',
            capture: 'environment',
            tabindex: -1,
            'data-js-qr-code-scanner': true,
            'data-js-qr-code-map': wallets.map { |w| [w.user.qr_code, w.id] }.to_h.to_json }
      = f.select :receiver_wallet_id,
        wallets.map { |w| [w.user.name +  (w.user.regular? ? ": #{w.balance} #{w.currency.name_plural.titleize}" : ''), w.id] },
        { include_blank: true },
        class: 'form-control',
        'data-js-select-input': true,
        'data-js-qr-code-scanner-result': true
    .form-group
      = f.label :amount
      = f.select :amount,
        amounts.map { |am| [am.to_s, am] },
        { include_blank: true },
        class: 'form-control',
        'data-js-select-input': true,
        'data-js-select-input-createable': true
    = f.submit 'Send', class: 'btn btn-primary col-lg-6'
  - if current_user.merchant?
    %br
    %br
    = link_to 'Transaction Histoy', order_transactions_path, class: 'text-white'

= content_for :js do
  = javascript_include_tag '//rawgit.com/sitepoint-editors/jsqrcode/master/src/qr_packed.js'

app/views/order_transactions/redeem.html.haml
.col-lg-5.my-auto.mx-auto
  %h2.text-center= "Redeem #{Currency.days_of_air_time.first.name_plural.titleize}"
  = form_for resource do |f|
    = f.hidden_field :receiver_wallet_id
    .form-group
      = f.label :amount
      = f.select :amount,
        amounts.map { |am| [am.to_s, am] },
        { include_blank: true },
        class: 'form-control',
        'data-js-select-input': true,
        'data-js-select-input-createable': true
    = f.submit 'Send', class: 'btn btn-primary col-lg-6'